[package]
name = "athlesia_recursive_world_model_revision_abstraction_composition_generalization"
version = "0.1.0"
edition = "2021"

[dependencies]
athlesia_recursive_world_model = { path = "../athlesia_recursive_world_model" }
athlesia = { path = "../.." }
athlesia_cross_level = { path = "../athlesia_cross_level" }
athlesia_recursive = { path = "../athlesia_recursive" }
athlesia_recursive_world_model_revision_abstraction = { path = "../athlesia_recursive_world_model_revision_abstraction" }
athlesia_recursive_world_model_revision_abstraction_composition = { path = "../athlesia_recursive_world_model_revision_abstraction_composition" }
athlesia_recursive_world_model_revision_discovery = { path = "../athlesia_recursive_world_model_revision_discovery" }
